# Generated by Django 3.2 on 2021-11-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20211118_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_confirmation',
        ),
    ]
